{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "sentinel-gateway.fullname" . }}
  labels:
    {{- include "sentinel-gateway.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "sentinel-gateway.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
---
{{- if .Values.frontend.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "sentinel-gateway.fullname" . }}-frontend
  labels:
    {{- include "sentinel-gateway.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "sentinel-gateway.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
{{- end }}
{{- end }}
